<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.4.2" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>3e6bf5fa-d6c5-411e-9813-0890893f1f27</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Memofee\Memofee\Memofee.csproj" />
  </ItemGroup>

</Project>
